### ISSUE TITLE
macOS Sierra: Update to Launcher causes game to crash entirely. 

### ISSUE THREAD

**Issue by thatlexplays** [LRFLEW/OpenRCT2Launcher#26] opened 2016-10-22 04:31 UTC
Just updated the launcher to 0.0.6 and I now cannot launch the game period. 

Error Information below:

Process:               OpenRCT2 [24235]
Path:                  /Applications/OpenRCT2.app/Contents/MacOS/OpenRCT2
Identifier:            com.travis-ci.OpenRCT2
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           OpenRCT2 [24235]
User ID:               501

Date/Time:             2016-10-22 00:30:45.079 -0400
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        3732A221-FD68-A35C-F9BF-ED19A124E93D

Sleep/Wake UUID:       CAD8F19D-54E3-4C1E-B3E7-45213618207A

Time Awake Since Boot: 100000 seconds
Time Since Wake:       920 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/qt5/5.7.0/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /Applications/OpenRCT2.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Reason: image not found

Binary Images:
       0x10d662000 -        0x10d6a7ff7 +com.travis-ci.OpenRCT2 (0) <5CC6296B-9988-3126-9FFC-03ED1DC2903C> /Applications/OpenRCT2.app/Contents/MacOS/OpenRCT2
       0x10d6bc000 -        0x10dbb8fff +org.qt-project.QtWidgets (5.7 - 5.7.0) <6B999A10-F3E1-39EB-BF30-0037A77D97A1> /Applications/OpenRCT2.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10dd17000 -        0x10e166fe7 +org.qt-project.QtGui (5.7 - 5.7.0) <9143ECB9-21C1-3FB5-BC4D-9D1097CEABF6> /Applications/OpenRCT2.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10e25e000 -        0x10e779fff +org.qt-project.QtCore (5.7 - 5.7.0) <8E060509-06BA-3F20-98DE-2B8E0DED4BAF> /Applications/OpenRCT2.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10e828000 -        0x10e931ff7 +org.qt-project.QtNetwork (5.7 - 5.7.0) <5F3ED85C-9B0F-3075-80B5-80DAEF97CF8C> /Applications/OpenRCT2.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10e976000 -        0x10e97affb  com.apple.agl (3.3.1 - AGL-3.3.1) <47E88CED-4D65-3579-A730-B576D3E41DFA> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
       0x11a4ee000 -        0x11a52b1c7  dyld (421.1) <A525EAEA-AF86-30C2-B360-3D093B4F0828> /usr/lib/dyld
    0x7fffd154b000 -     0x7fffd1550fff  com.apple.DiskArbitration (2.7 - 2.7) <566D5C06-13E8-3638-B2EC-2B834D5F04F1> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fffd1c3b000 -     0x7fffd1cd0fff  com.apple.framework.IOKit (2.0.2 - 1324.1.7) <10BDCD1E-0463-3C53-BF11-C9A0919C1588> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fffd4aef000 -     0x7fffd4afdfff  com.apple.opengl (12.4.2 - 12.4.2) <06F5BF0B-BD03-361D-9D7B-626517E4F761> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fffe37b0000 -     0x7fffe37b1ff3  libSystem.B.dylib (1238) <168B3C56-081B-3998-9A44-681EB4C6828F> /usr/lib/libSystem.B.dylib
    0x7fffe38c1000 -     0x7fffe38c1ff3  libauto.dylib (187) <5BBF6A00-CC76-389D-84E7-CA88EDADE683> /usr/lib/libauto.dylib
    0x7fffe38e2000 -     0x7fffe3938ff7  libc++.1.dylib (307.4) <BEE86868-F831-384C-919E-2B286ACFE87C> /usr/lib/libc++.1.dylib
    0x7fffe3939000 -     0x7fffe3963fff  libc++abi.dylib (307.2) <1CEF8ABB-7E6D-3C2F-8E0A-E7884478DD23> /usr/lib/libc++abi.dylib
    0x7fffe4452000 -     0x7fffe4822d97  libobjc.A.dylib (706) <F9AFE665-A3A2-3285-9495-19803A565861> /usr/lib/libobjc.A.dylib
    0x7fffe4c48000 -     0x7fffe4c59ff3  libz.1.dylib (67) <46E3FFA2-4328-327A-8D34-A03E20BFFB8E> /usr/lib/libz.1.dylib
    0x7fffe4c68000 -     0x7fffe4c6cff7  libcache.dylib (79) <84E55656-FDA9-3B29-9E4F-BE31B2C0AA3C> /usr/lib/system/libcache.dylib
    0x7fffe4c6d000 -     0x7fffe4c77fff  libcommonCrypto.dylib (60092.1.2) <79F738D8-0AD7-3DEA-AF80-E0F8B90B74E3> /usr/lib/system/libcommonCrypto.dylib
    0x7fffe4c78000 -     0x7fffe4c7ffff  libcompiler_rt.dylib (62) <486BDE52-81B4-3446-BD72-23977CAE556F> /usr/lib/system/libcompiler_rt.dylib
    0x7fffe4c80000 -     0x7fffe4c88fff  libcopyfile.dylib (138) <0DA49B77-56EC-362D-98FF-FA78CFD986D6> /usr/lib/system/libcopyfile.dylib
    0x7fffe4c89000 -     0x7fffe4d0bff3  libcorecrypto.dylib (442.1.3) <1CA8B679-810E-3C04-945A-4AC19372CDC7> /usr/lib/system/libcorecrypto.dylib
    0x7fffe4d0c000 -     0x7fffe4d3efff  libdispatch.dylib (703.1.4) <12B1D95B-283D-325D-85AB-29A2FFD36987> /usr/lib/system/libdispatch.dylib
    0x7fffe4d3f000 -     0x7fffe4d44ff3  libdyld.dylib (421.1) <CDFBDC9C-418C-369D-B433-F64B0630E640> /usr/lib/system/libdyld.dylib
    0x7fffe4d45000 -     0x7fffe4d45ffb  libkeymgr.dylib (28) <09CD7CA6-46D2-3A9F-B9F1-7C4CA5CA0D68> /usr/lib/system/libkeymgr.dylib
    0x7fffe4d53000 -     0x7fffe4d53fff  liblaunch.dylib (972.1.5) <DC31FDEA-FD81-335E-BAA8-5A7395D20772> /usr/lib/system/liblaunch.dylib
    0x7fffe4d54000 -     0x7fffe4d59fff  libmacho.dylib (894) <1EAE5ADD-490C-3B1F-9F97-447BA8E0E90F> /usr/lib/system/libmacho.dylib
    0x7fffe4d5a000 -     0x7fffe4d5cff3  libquarantine.dylib (85) <78EF62D8-C890-3FC0-937A-C2FD8CEF8992> /usr/lib/system/libquarantine.dylib
    0x7fffe4d5d000 -     0x7fffe4d5effb  libremovefile.dylib (45) <C4FC07FF-ED86-382E-B06F-33C34718080C> /usr/lib/system/libremovefile.dylib
    0x7fffe4d5f000 -     0x7fffe4d77ff7  libsystem_asl.dylib (349.1.1) <F0987490-8427-367F-B302-A05A7D61FEBF> /usr/lib/system/libsystem_asl.dylib
    0x7fffe4d78000 -     0x7fffe4d78ff7  libsystem_blocks.dylib (67) <B8C3701D-5A91-3D35-999D-2DC8D5393525> /usr/lib/system/libsystem_blocks.dylib
    0x7fffe4d79000 -     0x7fffe4e06fe7  libsystem_c.dylib (1158.1.2) <5F260836-48E4-3F57-8553-62D2DA228A1F> /usr/lib/system/libsystem_c.dylib
    0x7fffe4e07000 -     0x7fffe4e0affb  libsystem_configuration.dylib (888.1.2) <67BB9D8B-2430-38AD-81A7-F0EC924B2590> /usr/lib/system/libsystem_configuration.dylib
    0x7fffe4e0b000 -     0x7fffe4e0efff  libsystem_coreservices.dylib (41.1) <11F22E6C-0DCB-3699-A4F0-C99E301E56E9> /usr/lib/system/libsystem_coreservices.dylib
    0x7fffe4e0f000 -     0x7fffe4e27ffb  libsystem_coretls.dylib (121.1.1) <8F7E9B12-400D-3276-A9C5-4546B0258554> /usr/lib/system/libsystem_coretls.dylib
    0x7fffe4e28000 -     0x7fffe4e2efff  libsystem_dnssd.dylib (765.1.2) <C5FF2025-C60B-39C6-B205-6BF1BC51D1B3> /usr/lib/system/libsystem_dnssd.dylib
    0x7fffe4e2f000 -     0x7fffe4e58fff  libsystem_info.dylib (503) <C686B834-5E7D-382C-AF6E-44AB78EE83E2> /usr/lib/system/libsystem_info.dylib
    0x7fffe4e59000 -     0x7fffe4e7bff7  libsystem_kernel.dylib (3789.1.32) <5C68A0D7-C3C9-3E52-B983-EDE9A28AB6FC> /usr/lib/system/libsystem_kernel.dylib
    0x7fffe4e7c000 -     0x7fffe4ec3fe7  libsystem_m.dylib (3121.4) <E3370D16-EBAA-3C7F-AC56-2D6EAD7DB0A4> /usr/lib/system/libsystem_m.dylib
    0x7fffe4ec4000 -     0x7fffe4ee2ff7  libsystem_malloc.dylib (116) <3DD17B88-B7A4-38B9-9E95-AB88E1C3B647> /usr/lib/system/libsystem_malloc.dylib
    0x7fffe4ee3000 -     0x7fffe4f39fff  libsystem_network.dylib (856.1.8) <A8973360-956A-33BF-9971-14D59C84E0D1> /usr/lib/system/libsystem_network.dylib
    0x7fffe4f3a000 -     0x7fffe4f43ff3  libsystem_networkextension.dylib (563.1.11) <1C551832-9360-36DD-A7BA-52B55A171720> /usr/lib/system/libsystem_networkextension.dylib
    0x7fffe4f44000 -     0x7fffe4f4dffb  libsystem_notify.dylib (165) <AF77D471-6B13-36BA-B144-7E7DDB9DBA9F> /usr/lib/system/libsystem_notify.dylib
    0x7fffe4f4e000 -     0x7fffe4f56fe7  libsystem_platform.dylib (126.1.2) <884DDF42-3CAE-334A-82CE-965617130FB1> /usr/lib/system/libsystem_platform.dylib
    0x7fffe4f57000 -     0x7fffe4f61fff  libsystem_pthread.dylib (218.1.3) <050AE77B-4F4B-334A-A5BA-CF0D10AF5304> /usr/lib/system/libsystem_pthread.dylib
    0x7fffe4f62000 -     0x7fffe4f65fff  libsystem_sandbox.dylib (592.1.3) <90FEF628-316D-3F84-9EF4-F7F510A4FBBB> /usr/lib/system/libsystem_sandbox.dylib
    0x7fffe4f66000 -     0x7fffe4f67fff  libsystem_secinit.dylib (24) <A54B8FEF-E792-3C54-8E0B-E80A376662F2> /usr/lib/system/libsystem_secinit.dylib
    0x7fffe4f68000 -     0x7fffe4f6ffff  libsystem_symptoms.dylib (532.1.1) <B26F656E-94F9-3834-9B03-51C4FF11D1BF> /usr/lib/system/libsystem_symptoms.dylib
    0x7fffe4f70000 -     0x7fffe4f90ff7  libsystem_trace.dylib (518.1.16) <C3CDF7BC-CA3D-34F5-ADF8-46AAAB0B47F8> /usr/lib/system/libsystem_trace.dylib
    0x7fffe4f91000 -     0x7fffe4f96ffb  libunwind.dylib (35.3) <9F7C2AD8-A9A7-3DE4-828D-B0F0F166AAA0> /usr/lib/system/libunwind.dylib
    0x7fffe4f97000 -     0x7fffe4fc0ff7  libxpc.dylib (972.1.5) <2A901937-48E1-3BF2-83F1-2431156D82B7> /usr/lib/system/libxpc.dylib

**Comment by LRFLEW** [comment] 2016-10-22 04:55
Odd. I do most of my development of OpenRCT2 and the Launcher on my Mac running Sierra, so I'm surprised. I'll look into it.

EDIT: I'm getting the crash too. It appears to be a problem with the Travis build. I'll fix it. In the mean time, feel free to stick with v0.0.5. Because of the way that macOS was updated, the older versions of the launcher can get the 64-bit builds as well.

**Comment by LRFLEW** [comment] 2016-10-22 05:14
I figured out the core of the issue. The problem is that the version of Qt5 that's been setup with Homebrew (which is what I use as part of the automated build process) has an issue that prevents `macdeployqt` (another tool used in the automated build process) from working properly. I'll report that issue to them. In the mean time, I'll setup another build that works around the issue. It will be up in an hour or so.

**Comment by LRFLEW** [comment] 2016-10-22 07:07
I've added a new build to the release. I've tested this build on a "clean" machine, and it worked. I'm closing the issue now. If you are still having issues, leave a comment here and I can reopen the issue.

**Closed as completed by LRFLEW** 2016-10-22 07:07 UTC
