### ISSUE TITLE
Select Target Version in launcher

### ISSUE THREAD

**Issue by FlightMS** [LRFLEW/OpenRCT2Launcher#61] opened 2021-05-03 09:26 UTC
It would be nice if you can choose the version which is used by the updater, like in the Minecraft lauchner.

- Newest Version
- 0.3.3
- 0.3.2
- 0.3.0
- and so on

**Comment by Margen67** [comment] 2021-07-24 09:30
Duplicate of #30

**Closed as completed** 2021-07-24 11:18 UTC
